apiVersion: v1
kind: Pod
metadata:
    name: dataaccess
spec:
    containers:
    - name: alpine
      image: alpine:latest
      command: ['sleep', 'infinity']
      volumeMounts:
      - name: dbench-pv-claim
        mountPath: /data
    volumes:
    - name: dbench-pv-claim
      persistentVolumeClaim:
        claimName: dbench-pv-claim
